### ISSUE TITLE
fxcmpy.ServerError: Can not connect to FXCM Server

### ISSUE THREAD

**Issue by nadeeja9** [fxcm/3rd-party-oauth#2]
Cannot connect to the server . 

Tested with a plain vanilla sample code.

I have tried with previously working instances. 

Appreciate your help.

**Comment by FXCMAPI** [comment]
Dear client

Does your code or token worked ever before?
What is the error logs or screen shot?

For demo account, please provide demo token for further investigation

Best regards
Lei


CFDs are complex instruments and come with a high risk of losing money rapidly due to leverage.

76.31% of retail investor accounts lose money when trading CFDs with this provider.

You should consider whether you understand how CFDs work and whether you can afford to take the high risk of losing your money.

Trading Forex/CFDs on margin carries a high level of risk and may not be suitable for all investors. Leverage can work against you. The products are intended for retail, professional and eligible counterparty clients. Retail clients who maintain account(s) with Forex Capital Markets Limited ("FXCM LTD") could sustain a total loss of deposited funds but are not subject to subsequent payment obligations beyond the deposited funds but professional clients and eligible counterparty clients could sustain losses in excess of deposits. Clients who maintain account(s) with FXCM Australia Pty. Limited (“FXCM AU”), FXCM South Africa (PTY) Ltd (“FXCM ZA”) or FXCM Markets Limited (“FXCM Markets”) could sustain losses in excess of deposits. Prior to trading any products offered by FXCM LTD<https://www.fxcm.com/uk/>, inclusive of all EU branches, FXCM AU<https://www.fxcm.com/au/>, FXCM ZA<https://www.fxcm.com/za/>, any affiliates of aforementioned firms, or other firms within the FXCM group of companies [collectively the “FXCM Group”], carefully consider your financial situation and experience level. If you decide to trade products offered by FXCM Australia Pty. Limited (“FXCM AU”) (AFSL 309763), you must read and understand the Financial Services Guide<https://docs.fxcorporate.com/financial-services-guide-au.pdf>, Product Disclosure Statement<https://www.fxcm.com/au/legal/product-disclosure-statements/>, and Terms of Business<https://docs.fxcorporate.com/tob_au_en.pdf>. Our FX and CFD prices are set by us, are not made on an Exchange and are not governed under the Financial Advisory and Intermediary Services Act. The FXCM Group may provide general commentary which is not intended as investment advice and must not be construed as such. Seek advice from a separate financial advisor. The FXCM Group assumes no liability for errors, inaccuracies or omissions; does not warrant the accuracy, completeness of information, text, graphics, links or other items contained within these materials. Read and understand the Terms and Conditions on the FXCM Group’s websites prior to taking further action.

The FXCM Group is headquartered at 20 Gresham Street, 4th Floor, London EC2V 7JE, United Kingdom. Forex Capital Markets Limited (“FXCM LTD”) is authorised and regulated in the UK by the Financial Conduct Authority. Registration number 217689. Registered in England and Wales with Companies House company number 04072877. FXCM Australia Pty. Limited (“FXCM AU”) is regulated by the Australian Securities and Investments Commission, AFSL 309763. FXCM AU ACN: 121934432. The information provided by FXCM AU is intended for residents of Australia and is not directed at any person in any country or jurisdiction where such distribution or use would be contrary to local law or regulation. Please read the full Terms and Conditions<https://www.fxcm.com/au/legal/terms-conditions/>. FXCM South Africa (PTY) Ltd is an authorized Financial Services Provider and is regulated by the Financial Sector Conduct Authority under FSP No 46534. FXCM Markets Limited ("FXCM Markets") is incorporated in Bermuda as an operating subsidiary within the FXCM group. FXCM Markets is not required to hold any financial services license or authorization in Bermuda to offer its products and services. FXCM Global Services, LLC is an operating subsidiary within the FXCM Group. FXCM Global Services, LLC is not regulated and not subject to regulatory oversight.
From: nadeeja9 ***@***.***>
Sent: Wednesday, March 10, 2021 3:18 PM
To: fxcm/3rd-party-oauth ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fxcm/3rd-party-oauth] fxcmpy.ServerError: Can not connect to FXCM Server (#2)


Cannot connect to the server .

Tested with a plain vanilla sample code.

I have tried with previously working instances.

Appreciate your help.

**Comment by nadeeja9** [comment]
HI Lei, 

I had renewed my code yesterday. 

Please find the demo account token 480e34dfd8bb3226987d9dbab067314e650b96af

I have tried the attached code:

![Screenshot 2021-03-11 130905](https://user-images.githubusercontent.com/2256298/110763255-1a57b800-826b-11eb-8ca8-18c1d5efba4d.jpg)
![Screenshot 2021-03-11 130946](https://user-images.githubusercontent.com/2256298/110763258-1af04e80-826b-11eb-8c3b-787dc1a255b8.jpg)

**Comment by FXCM-ValentinMandev** [comment]
Hi,

Your token is working okay.

Can you please check your python-engineio version:
import engineio
print(engineio.__version__)
 
If it’s version 4, please downgrade to 3.9
python -m pip install python-engineio==3.9
 
If this doesn’t solve the problem you can also downgrade python-socketio to 4.4 or 4.6.1.

Best Regards,
Valentin

**Comment by nadeeja9** [comment]
HI, 

I Had:
----------------------------------------
The Python 3.8.5
Socketio version 5.1.0
----------------------------------------
This does not work. 

I have now downgraded socketio  to version 4.6.1 which worked. 

Thanks for your help.
